### ISSUE TITLE
WiFi HID emulator

### ISSUE THREAD

**Issue by mkeyno** [ArthurYidi/Houdini-Joystick#1]
hi , sorry to open a ticket for my question, but I have a question that may related to your field of repository and any possible hint really appreciated
Actually I interested to send game-pad data by WiFi bridge to my laptop, but generic joystick only use USB port, Is there a way to emulate "HID-compliant game controller" driver which listen to IP message instead of USB port
Tnx

**Comment by ArthurYidi** [comment]
> Is there a way to emulate "HID-compliant game controller" driver which listen to IP message instead of USB port

No solutions that I'm aware of, and wouldn't recommend such a solution.

Sounds like you might want to use something like OSC (Open Sound Protocol).
